name: "Todo Checker"

on:
  pull_request: ["dev"]

jobs:
  todo-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run Todo Checker
        run: npx todo-checker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
